name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  codebase:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Attempt a rebase
        run: |
          git config --global advice.detachedHead "false"
          git checkout -b ${{ github.base_ref }}
          git branch -u origin/${{ github.base_ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          git rebase ${{ github.base_ref }}

  black:
    needs: codebase
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Black 3.7
        run: |
          docker run \
          --rm \
          -v "$PWD:/app" \
          ghcr.io/connecting-food/python-quality-assurance:master \
          black . -tpy37 -l80

  flake8:
    needs: codebase
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Flake8
        run: |
          pip install flake8 && \
          flake8 --select=C,E,F,W \
            --max-line-length 80 \
            --max-complexity 15 \
            --ignore=W503

  lint-dockerfile:
    needs: [black, flake8]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        run: |
          docker run \
          --rm \
          -v "$PWD"/app/Dockerfile:/dockerfilelinter/Dockerfile \
          petitnuage/dockerfile-linter:latest \
          linter \
          -i EC0001,EF0004,ER0001,ER0007,ER0012,ER0013,EU0001 \
          -f Dockerfile